/*
 * This source file was generated by the Gradle 'init' task
 */
package assigment2;

import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertSame;
import static org.junit.jupiter.api.Assertions.assertTrue;
import org.junit.jupiter.api.Test;

class AppTest {
    @Test
    void testSingletonInstance() {
        ConfigurationManager instance1 = ConfigurationManager.getInstance();
        ConfigurationManager instance2 = ConfigurationManager.getInstance();
        assertSame(instance1, instance2, "Both instances should be the same");
    }

    @Test
    void testShapeFactory() {
        ShapeFactory shapeFactory = new ShapeFactory();

        Shape circle = shapeFactory.getShape("CIRCLE");
        assertNotNull(circle, "ShapeFactory should create a Circle");
        assertTrue(circle instanceof Circle, "Shape should be an instance of Circle");

        Shape square = shapeFactory.getShape("SQUARE");
        assertNotNull(square, "ShapeFactory should create a Square");
        assertTrue(square instanceof Square, "Shape should be an instance of Square");
    }
}
