/*
 * This source file was generated by the Gradle 'init' task
 */
package assigment2;

public class DemoApp {
    public static void main(String[] args) {
        //Singleton Pattern
        ConfigurationManager configManager = ConfigurationManager.getInstance();
        String value = configManager.getConfigValue("someKey");
        System.out.println("Config Value: " + value);

        ShapeFactory shapeFactory = new ShapeFactory();

        //Factory Pattern
        Shape shape1 = shapeFactory.getShape("CIRCLE");
        shape1.draw();
        Shape shape2 = shapeFactory.getShape("SQUARE");
        shape2.draw();
    }
}
